apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-cm"
  namespace: {{ .Values.namespace }}
data:
  service.email: |
    host: {{ .Values.email.host }}
    port: {{ .Values.email.port }}
    from: {{ .Values.email.gmailuser }}
    username: {{ .Values.email.gmailuser }}
    password: "vdpabziockamatef"

  subscriptions: |
    - recipients:
        - "email:{{ .Values.email.recipients.email1 }}"
        - "email:{{ .Values.email.recipients.email2 }}"
      triggers:
        - on-sync-succeeded

  template.app-created: |
    email:
      subject: Application {{ "{{ .app.metadata.name }}" }} has been created.
    message: Application {{ "{{ .app.metadata.name }}" }} has been created.

  template.app-deleted: |
    email:
      subject: Application {{ "{{ .app.metadata.name }}" }} has been deleted.
    message: Application {{ "{{ .app.metadata.name }}" }} has been deleted.

  template.app-deployed: |
    email:
      subject: New version of an application {{ "{{ .app.metadata.name }}" }} is up and running.
    message: |
      Application {{ "{{ .app.metadata.name }}" }} is now running new version of deployment manifests.
      Details: {{ "{{ .context.argocdUrl }}" }}/applications/{{ "{{ .app.metadata.name }}" }}

  template.app-health-degraded: |
    email:
      subject: Application {{ "{{ .app.metadata.name }}" }} has degraded.
    message: |
      Application {{ "{{ .app.metadata.name }}" }} has degraded.
      Application details: {{ "{{ .context.argocdUrl }}" }}/applications/{{ "{{ .app.metadata.name }}" }}

  template.app-sync-failed: |
    email:
      subject: Failed to sync application {{ "{{ .app.metadata.name }}" }}.
    message: |
      The sync operation of application {{ "{{ .app.metadata.name }}" }} has failed at {{ "{{ .app.status.operationState.finishedAt }}" }}
      Error: {{ "{{ .app.status.operationState.message }}" }}

      Details:
      {{ "{{ .context.argocdUrl }}" }}/applications/{{ "{{ .app.metadata.name }}" }}?operation=true

  template.app-sync-running: |
    email:
      subject: Start syncing application {{ "{{ .app.metadata.name }}" }}.
    message: |
      The sync operation of application {{ "{{ .app.metadata.name }}" }} started at {{ "{{ .app.status.operationState.startedAt }}" }}.

      Details:
      {{ "{{ .context.argocdUrl }}" }}/applications/{{ "{{ .app.metadata.name }}" }}?operation=true

  template.app-sync-status-unknown: |
    email:
      subject: Application {{ "{{ .app.metadata.name }}" }} sync status is 'Unknown'
    message: |
      Application {{ "{{ .app.metadata.name }}" }} sync status is 'Unknown'.

      Details:
      {{ "{{ range $c := .app.status.conditions }}" }}
      - {{ "{{ $c.message }}" }}
      {{ "{{ end }}" }}

  template.app-sync-succeeded: |
    email:
      subject: Application {{ "{{ .app.metadata.name }}" }} has been successfully synced.
    message: |
      Application {{ "{{ .app.metadata.name }}" }} has been successfully synced at {{ "{{ .app.status.operationState.finishedAt }}" }}.

      Details:
      {{ "{{ .context.argocdUrl }}" }}/applications/{{ "{{ .app.metadata.name }}" }}?operation=true

  trigger.on-created: |
    - description: Application is created.
      oncePer: app.metadata.name
      send:
      - app-created
      when: "true"

  trigger.on-deleted: |
    - description: Application is deleted.
      oncePer: app.metadata.name
      send:
      - app-deleted
      when: app.metadata.deletionTimestamp != nil

  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.operationState?.syncResult?.revision
      send:
      - app-deployed
      when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
        and app.status.health.status == 'Healthy'

  trigger.on-health-degraded: |
    - description: Application has degraded
      oncePer: app.status.operationState?.syncResult?.revision
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'

  trigger.on-sync-failed: |
    - description: Application syncing has failed
      oncePer: app.status.operationState?.syncResult?.revision
      send:
      - app-sync-failed
      when: app.status.operationState != nil and app.status.operationState.phase in ['Error','Failed']

  trigger.on-sync-running: |
    - description: Application is being synced
      oncePer: app.status.operationState?.syncResult?.revision
      send:
      - app-sync-running
      when: app.status.operationState != nil and app.status.operationState.phase in ['Running']

  trigger.on-sync-status-unknown: |
    - description: Application status is 'Unknown'
      oncePer: app.status.operationState?.syncResult?.revision
      send:
      - app-sync-status-unknown
      when: app.status.sync.status == 'Unknown'

  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      oncePer: app.status.operationState?.syncResult?.revision
      send:
      - app-sync-succeeded
      when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']